### ISSUE TITLE
IDEA: Consider a native app wrapper

### ISSUE THREAD

**Issue by WheresHJ** [codeforboston/mbta-ninja#60] opened 2015-02-25 17:20 UTC
Might be good to get this in the various app stores, so perhaps a PhoneGap wrapper would be interesting to explore. We can help to get iOS and Android dev licenses for you at CfB.

**Comment by JacobEvelyn** [comment] 2015-02-25 23:07
Meteor plugs in really easily with PhoneGap, just FYI.

**Comment by radhikamalik** [comment] 2015-09-08 23:33
@WheresHJ still waiting on the iOS license!

**Comment by radhikamalik** [comment] 2015-09-08 23:42
Closing since duplicate of #135

**Closed as completed by radhikamalik** 2015-09-08 23:42 UTC
